pipeline {
    agent any

    tools {
        maven "M3"
        jdk "JDK11"
    }

    stages {
        stage('Git Clone') {
            steps {
                echo 'Git Clone'
                git url: 'https://github.com/ahfkenehla/spring-petclinic.git',
                branch: 'main', credentialsId: 'gitCredentials'
            }
            
        }
        stage('Build') {
            steps {
                echo 'Build'
            }
        }
        stage('Docker Image') {
            steps {
                echo 'Docker Image'
            }
        }
        stage('Docker Push') {
            steps {
                echo 'Docker Push'
            }
        }
        stage('Target Pull') {
            steps {
                echo 'Target Pull'
            }
        }
    }
}
