pipeline {
    agent any

    tools {
        maven "M3"
        jdk "JDK11"
    }

    stages {
        stage('Git Clone') {
            steps {
                echo 'Git Clone'
                git url: 'https://github.com/ahfkenehla/spring-petclinic.git',
                branch: 'main', credentialsId: 'gitCredentials'
            }
            post {
                success {
                    echo 'Git Clone Success'
                }
                failure {
                    echo 'Git Clone Fail'
                }
            }
        }
        stage('Build') {
            steps {
                echo 'Build'
                sh 'mvn -Dmaven.test.failure.ignore=true clean package'
            }
            post {
                success {
                    junit 'target/surefire-reports/**/*.xml'
                }
            }
        }
        stage('Docker Build') {
            steps {
                echo 'Docker Build'
            }
        }
        stage('Docker Push') {
            steps {
                echo 'Docker Push'
            }
        }
        stage('Target CD') {
            steps {
                echo 'Target CD'
            }
        }
    }
}
